[project]
name = "url"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autopep8>=2.3.2",
    "flake8>=7.3.0",
    "flake8-bugbear>=25.11.29",
    "flake8-docstrings>=1.7.0",
    "matplotlib>=3.10.8",
    "nbqa>=1.9.1",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
]
